name: CI

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc*'
  pull_request:
    branches:
      - main

jobs:
  pre_build:
    if: |
      ${{!github.ref_type == 'tag' && !github.ref_name == 'main'}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Build Project
        run: yarn build
